# Generated by Django 4.1.7 on 2023-05-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_conversationlog_result"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordStartTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
