# Generated by Django 4.1.7 on 2023-05-06 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_recordstarttime"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecordStartTime",
        ),
    ]
