# Generated by Django 4.1.7 on 2023-04-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationLog",
            fields=[
                ("log_id", models.IntegerField(primary_key=True, serialize=False)),
                ("content", models.TextField(blank=True)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("result", models.IntegerField(blank=True)),
            ],
            options={
                "verbose_name": "Conversation Log",
                "verbose_name_plural": "Conversation Log",
            },
        ),
    ]
