# Generated by Django 4.1.7 on 2023-04-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_conversationlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationlog",
            name="log_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
