# Generated by Django 4.1.7 on 2023-04-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbuseDictionary",
            fields=[
                ("morpheme", models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Abuse Dictionary",
                "verbose_name_plural": "Abuse Dictionary",
            },
        ),
        migrations.CreateModel(
            name="CounselorDictionary",
            fields=[
                ("morpheme", models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Counselor Dictionary",
                "verbose_name_plural": "Counselor Dictionary",
            },
        ),
        migrations.CreateModel(
            name="SexualDictionary",
            fields=[
                ("morpheme", models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Sexual Dictionary",
                "verbose_name_plural": "Sexual Dictionary",
            },
        ),
    ]
